ALLOWED_TAGS = restaurant_tags = [
    # Cuisine / Region
    "american",
    "new_american",
    "southern",
    "bbq",
    "mexican",
    "tex_mex",
    "latin_american",
    "peruvian",
    "brazilian",
    "argentinian",
    "caribbean",
    "cuban",

    "italian",
    "pizza",
    "pasta",
    "french",
    "spanish",
    "tapas",
    "greek",
    "mediterranean",
    "middle_eastern",
    "lebanese",
    "turkish",
    "moroccan",

    "japanese",
    "sushi",
    "ramen",
    "izakaya",
    "korean",
    "korean_bbq",
    "chinese",
    "dim_sum",
    "hot_pot",
    "thai",
    "vietnamese",
    "pho",
    "indian",
    "pakistani",
    "filipino",
    "malaysian",
    "indonesian",

    "african",
    "ethiopian",
    "nigerian",
    "fusion",

    # Food Type / Specialty
    "seafood",
    "steakhouse",
    "burgers",
    "sandwiches",
    "tacos",
    "noodles",
    "dumplings",
    "fried_chicken",
    "wings",
    "salads",
    "soup",
    "bakery",
    "dessert",
    "ice_cream",
    "coffee",
    "brunch",
    "breakfast",
    "comfort_food",
    "small_plates",
    "shareable_plates",
    "tasting_menu",

    # Dietary / Health
    "vegan",
    "vegetarian",
    "plant_based",
    "gluten_free",
    "dairy_free",
    "nut_free_options",
    "halal",
    "kosher",
    "pescatarian",
    "keto_friendly",
    "low_carb",
    "low_calorie",
    "organic",
    "healthy",
    "clean_eating",
    "high_protein",

    # Price / Value
    "cheap_eats",
    "budget_friendly",
    "moderate_price",
    "expensive",
    "fine_dining",
    "good_value",
    "large_portions",
    "splurge_worthy",

    # Service Style
    "fast_service",
    "counter_service",
    "table_service",
    "takeout",
    "delivery",
    "drive_through",
    "food_truck",
    "buffet",
    "all_you_can_eat",
    "reservation_recommended",
    "walk_in_friendly",
    "late_night",

    # Occasion
    "date_night",
    "family_friendly",
    "group_friendly",
    "solo_friendly",
    "business_meeting",
    "celebration",
    "birthday",
    "anniversary",
    "casual",
    "quick_bite",
    "special_occasion",
    "tourist_friendly",

    # Atmosphere / Vibe
    "cozy",
    "trendy",
    "romantic",
    "upscale",
    "casual_vibe",
    "lively",
    "quiet",
    "intimate",
    "modern",
    "traditional",
    "rustic",
    "hipster",
    "family_style",
    "sports_bar",
    "neighborhood_spot",
    "hidden_gem",

    # Amenities / Setting
    "outdoor_seating",
    "patio",
    "rooftop",
    "waterfront",
    "scenic_view",
    "live_music",
    "bar_seating",
    "full_bar",
    "cocktails",
    "wine_bar",
    "beer",
    "parking_available",
    "wheelchair_accessible",
    "pet_friendly",

    # Experience Signals
    "authentic",
    "chef_driven",
    "locally_sourced",
    "farm_to_table",
    "seasonal_menu",
    "creative_menu",
    "classic_menu",
    "generous_portions",
    "highly_rated",
    "popular",
    "instagrammable",
    "unique_experience",

    # Taste / Flavor Profile
    "spicy",
    "mild",
    "savory",
    "sweet",
    "umami",
    "rich",
    "light",
    "fresh",
    "smoky",
    "crispy",
    "grilled",
    "fried",
    "saucy",

    # Meal Time
    "breakfast_spot",
    "brunch_spot",
    "lunch_spot",
    "dinner_spot",
    "late_night_food",
    "dessert_spot",
    "coffee_spot"
]